baseurl: 'http://leechristopher722.github.io/portfolio'
title: johndoe
theme: hugo-coder
languagecode: en
defaultcontentlanguage: en
paginate: 20
disqusShortname: yourdiscussshortname
markup:
  highlight:
    style: github-dark
params:
  author: John Doe
  info: Full Stack DevOps and Magician
  description: John Doe's personal website
  keywords: 'blog,developer,personal'
  avatarurl: images/avatar.jpg
  faviconSVG: /img/favicon.svg
  favicon_32: /img/favicon-32x32.png
  favicon_16: /img/favicon-16x16.png
  since: 2019
  enableTwemoji: true
  colorScheme: auto
  hidecolorschemetoggle: false
  social:
    - name: Github
      icon: fa fa-github fa-2x
      weight: 1
      url: 'https://github.com/johndoe/'
    - name: Gitlab
      icon: fa fa-gitlab fa-2x
      weight: 2
      url: 'https://gitlab.com/johndoe/'
    - name: Twitter
      icon: fa fa-twitter fa-2x
      weight: 3
      url: 'https://twitter.com/johndoe/'
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
menu:
  main:
    - name: Blog
      weight: 1
      url: posts/
    - name: About
      weight: 2
      url: about/

